use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

// Generated by https://quicktype.io

#[derive(Serialize, Deserialize)]
pub struct SubRedditNew {
    pub kind: String,
    pub data: SubRedditNewData,
}

#[derive(Serialize, Deserialize)]
pub struct SubRedditNewData {
    pub after: String,
    pub dist: i64,
    pub modhash: String,
    pub geo_filter: String,
    pub children: Vec<Child>,
    pub before: Option<serde_json::Value>,
}

#[derive(Serialize, Deserialize)]
pub struct Child {
    pub kind: Kind,
    pub data: ChildData,
}

//There should be some way to automate this using the json

impl ChildData {
    pub fn approved_at_utc(&self) -> Option<&serde_json::Value> {
        self.extra.get(&"approved_at_utc".to_owned())
    }
    pub fn subreddit(&self) -> String {
        self.extra.get("subreddit").unwrap().to_string()
    }
    pub fn downs(&self) -> i64 {
        self.extra.get("downs").unwrap().as_i64().unwrap()
    }
    //Stay consistent
    pub fn secure_media_embed(&self) -> &MediaEmbed {
        &self.secure_media_embed
    }
    pub fn distinguished(&self) -> Option<&Distinguished> {
        self.distinguished.as_ref()
    }
}

#[derive(Serialize, Deserialize)]
pub struct ChildData {
    secure_media_embed: MediaEmbed,
    distinguished: Option<Distinguished>,

    #[serde(flatten)]
    extra: HashMap<String, Value>,
}

#[derive(Serialize, Deserialize)]
pub struct AllAwarding {
    pub giver_coin_reward: Option<i64>,
    pub subreddit_id: Option<serde_json::Value>,
    pub is_new: bool,
    pub days_of_drip_extension: i64,
    pub coin_price: i64,
    pub id: String,
    pub penny_donate: Option<i64>,
    pub award_sub_type: AwardSubType,
    pub coin_reward: i64,
    pub icon_url: String,
    pub days_of_premium: i64,
    pub tiers_by_required_awardings: Option<serde_json::Value>,
    pub resized_icons: Vec<ResizedIcon>,
    pub icon_width: i64,
    pub static_icon_width: i64,
    pub start_date: Option<serde_json::Value>,
    pub is_enabled: bool,
    pub awardings_required_to_grant_benefits: Option<serde_json::Value>,
    pub description: String,
    pub end_date: Option<serde_json::Value>,
    pub subreddit_coin_reward: i64,
    pub count: i64,
    pub static_icon_height: i64,
    pub name: String,
    pub resized_static_icons: Vec<ResizedIcon>,
    pub icon_format: Option<String>,
    pub icon_height: i64,
    pub penny_price: Option<i64>,
    pub award_type: AwardType,
    pub static_icon_url: String,
}

#[derive(Serialize, Deserialize)]
pub struct ResizedIcon {
    pub url: String,
    pub width: i64,
    pub height: i64,
}

#[derive(Serialize, Deserialize)]
pub struct FlairRichtext {
    pub e: AuthorFlairType,
    pub t: String,
}

#[derive(Serialize, Deserialize)]
pub struct GalleryData {
    pub items: Vec<Item>,
}

#[derive(Serialize, Deserialize)]
pub struct Item {
    pub media_id: String,
    pub id: i64,
}

#[derive(Serialize, Deserialize)]
pub struct Gildings {
    pub gid_1: Option<i64>,
}

#[derive(Serialize, Deserialize)]
pub struct Media {
    pub reddit_video: Option<RedditVideo>,
    #[serde(rename = "type")]
    pub media_type: Option<String>,
    pub oembed: Option<Oembed>,
}

#[derive(Serialize, Deserialize)]
pub struct Oembed {
    pub provider_url: String,
    pub version: String,
    pub title: String,
    #[serde(rename = "type")]
    pub oembed_type: String,
    pub thumbnail_width: i64,
    pub height: i64,
    pub width: i64,
    pub html: String,
    pub author_name: Option<String>,
    pub provider_name: String,
    pub thumbnail_url: String,
    pub thumbnail_height: i64,
    pub author_url: Option<String>,
    pub description: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct RedditVideo {
    pub bitrate_kbps: i64,
    pub fallback_url: String,
    pub height: i64,
    pub width: i64,
    pub scrubber_media_url: String,
    pub dash_url: String,
    pub duration: i64,
    pub hls_url: String,
    pub is_gif: bool,
    pub transcoding_status: String,
}

#[derive(Serialize, Deserialize)]
pub struct MediaEmbed {
    pub content: Option<String>,
    pub width: Option<i64>,
    pub scrolling: Option<bool>,
    pub height: Option<i64>,
    pub media_domain_url: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct MediaMetadatum {
    pub status: Status,
    pub e: String,
    pub m: String,
    pub p: Vec<String>,
    pub s: String,
    pub id: String,
}

#[derive(Serialize, Deserialize)]
pub struct S {
    pub y: i64,
    pub x: i64,
    pub u: String,
}

#[derive(Serialize, Deserialize)]
pub struct Preview {
    pub images: Vec<Image>,
    pub enabled: bool,
}

#[derive(Serialize, Deserialize)]
pub struct Image {
    pub source: ResizedIcon,
    pub resolutions: Vec<ResizedIcon>,
    pub variants: Variants,
    pub id: String,
}

#[derive(Serialize, Deserialize)]
pub struct Variants {
    pub gif: Option<Gif>,
    pub mp4: Option<Gif>,
}

#[derive(Serialize, Deserialize)]
pub struct Gif {
    pub source: ResizedIcon,
    pub resolutions: Vec<ResizedIcon>,
}

#[derive(Serialize, Deserialize)]
#[serde(untagged)]
pub enum Edited {
    Bool(bool),

    Double(f64),
}

#[derive(Serialize, Deserialize)]
pub enum AwardSubType {
    #[serde(rename = "GLOBAL")]
    Global,

    #[serde(rename = "PREMIUM")]
    Premium,
}

#[derive(Serialize, Deserialize)]
pub enum AwardType {
    #[serde(rename = "global")]
    Global,
}

#[derive(Serialize, Deserialize)]
pub enum AuthorFlairType {
    #[serde(rename = "richtext")]
    Richtext,

    #[serde(rename = "text")]
    Text,
}

#[derive(Serialize, Deserialize)]
pub enum Distinguished {
    #[serde(rename = "moderator")]
    Moderator,
}

#[derive(Serialize, Deserialize)]
pub enum LinkFlairTextColor {
    #[serde(rename = "dark")]
    Dark,

    #[serde(rename = "light")]
    Light,
}

#[derive(Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "valid")]
    Valid,
}

#[derive(Serialize, Deserialize)]
pub enum WhitelistStatus {
    #[serde(rename = "all_ads")]
    AllAds,

    #[serde(rename = "some_ads")]
    SomeAds,
}

#[derive(Serialize, Deserialize)]
pub enum PostHint {
    #[serde(rename = "hosted:video")]
    HostedVideo,

    #[serde(rename = "image")]
    Image,

    #[serde(rename = "link")]
    Link,

    #[serde(rename = "self")]
    PostHintSelf,
}

#[derive(Serialize, Deserialize)]
pub enum SubredditType {
    #[serde(rename = "public")]
    Public,

    #[serde(rename = "restricted")]
    Restricted,
}

#[derive(Serialize, Deserialize)]
pub enum SuggestedSort {
    #[serde(rename = "confidence")]
    Confidence,
}

#[derive(Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "t3")]
    T3,
}
