name: Run tests.

on:
  push:
    branches: [ main, modeling ]
  pull_request:
    branches: [ main, modeling ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cargo Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run:  cargo test --color=always --package reddit-api --lib tests --no-fail-fast -- --format=json -Z unstable-options --show-output
